{% set name = "gh" %}
{% set version = "2.68.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cli/cli/archive/v{{ version }}.tar.gz
  sha256: 520ab7ca5eda31af4aab717e1f9bc65497cdc23a46f71dab56d47513e00c7b82

build:
  number: 0
  script_env:
    - GH_VERSION=v{{ version }}

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - gh help
    - gh version

about:
  home: https://github.com/cli/cli
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Github CLI.
  description: |
    gh is GitHub on the command line. It brings pull requests, issues,
    and other GitHub concepts to the terminal next to where you are already working with git and your code.
  doc_url: https://cli.github.com/
  dev_url: https://github.com/cli/cli

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - matthiasdiener
